# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_points_A', models.PositiveSmallIntegerField(default=0)),
                ('round_points_B', models.PositiveSmallIntegerField(default=0)),
                ('round_points_C', models.PositiveSmallIntegerField(default=0)),
                ('play_date', models.DateTimeField(verbose_name='round played')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player_A', models.CharField(max_length=100)),
                ('player_B', models.CharField(max_length=100)),
                ('player_C', models.CharField(max_length=100)),
                ('points_A', models.PositiveSmallIntegerField(default=0)),
                ('points_B', models.PositiveSmallIntegerField(default=0)),
                ('points_C', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatabend.Round'),
        ),
    ]
