# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skatabend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('played_games', models.PositiveSmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='tournament_played',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='skatabend.Tournament'),
        ),
    ]
