# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skatabend', '0002_auto_20161021_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='last_played',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 25, 11, 13, 7, 527810, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='points',
            name='play_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
