# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skatabend', '0004_auto_20170205_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['last_played']},
        ),
    ]
