# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skatabend', '0005_auto_20170205_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='tournament_played',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='skatabend.Tournament'),
        ),
    ]
